# Example Snyk script for GitLab CI/CD Pipeline with Go Modules project

stages:
  - compile
build:
  stage: compile
  image: golang:1.14
  script:
    - go build -o binary
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install nodejs
    - npm install -g snyk
    # Install snyk-to-html to generate an html report within the GitLab repo
    # - npm install snyk-to-html -g
    # Run snyk auth, snyk monitor, snyk test to break build and output report
    - snyk auth $SNYK_TOKEN
    # Run snyk monitor to push results to Snyk UI and custom name the project
    - snyk monitor --project-name=go-goof-gitlab-CI2
    # Run snyk test to fail the build if vulns are found
    - snyk test
    # Add --json | snyk-to-html -o snyk_results.html to above to generate html report
  
  # Save the snyk-to html report to artifacts
  artifacts:
    when: always
    paths: 
      - snyk_results.html