# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

# Node.js tool installer
steps:
# Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'new_snyk_auth'
    testType: 'app'
    monitorOnBuild: true
    failOnIssues: true
    projectName: 'azure-goof-test'
    organization: 'org id'